[project]
name = "cv-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain-ollama>=1.0.1",
    "pydantic>=2.12.5",
    "streamlit>=1.52.2",
]
